name: Module 4 Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: HKZ012514
          POSTGRES_DB: gradcafe_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d gradcafe_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd module_4
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Initialize database
        run: |
          cd module_4
          python -m src.load_data
          
      - name: Run pytest
        run: |
          cd module_4
          python -m pytest tests